### ISSUE TITLE
Preserve Newlines

### ISSUE THREAD

**Issue by garretthyder** [10quality/ayuco#4]
Hello @amostajo 

Loving the ayuco tool.

One thing I found frustrating was after nicely formatting and commenting my Main.php I found running the ayuco to add additional entries (ex. add_shortcode) all the newlines are stripped between my commands and functions.

I feel this is the PHP-Parser and it's prettyprint function but am unsure how to preserve newlines.

**Comment by amostajo** [comment]
@garretthyder I know...

But this is not an issue with ayuco, is with the commands. Might need to fork PHP-Parses to preserve WordPress formatting. Closing this here, and adding the issue to the comands repo.

**Comment by garretthyder** [comment]
Awesome thanks @amostajo
