### ISSUE TITLE
Deprecate SetName?

### ISSUE THREAD

**Issue by garretthyder** [10quality/ayuco#9]
Hi @amostajo I was going to deprecate SetNameCommand in AYUCO here similar to what I did in wpmvc-commands here;
https://github.com/10quality/wpmvc-commands/issues/28

Before I dive in too deep wanted to make sure I'm going about this appropriately. 

In order to deprecate SetNameCommand I would have to introduce the SetCommand correct? Which looks to involve also introducing it's associated Trait setters; SetNamespaceTrait, SetVersionTrait, SetTextDomainTrait, SetAuthorTrait.

I wasn't sure if that's appropriate to add all those additional files so wanted to confirm with you before proceeding.

Thank you

**Comment by amostajo** [comment]
@garretthyder I think we should remove `SetNameCommand` and `SetupCommand` from Ayuco. To make it independent from WordPress MVC as it can be used on any PHP project. What do you think?

**Comment by garretthyder** [comment]
I think that makes sense and is a good idea, allows you to extend it's support to other projects. Both commands are already covered in wpmvc-commands I believe so as long as the modules are installed it should work without any change to the user experience.
